/**:
    ros__parameters:
      registration_method: "NDT_OMP"
      score_threshold: 2.0
      ndt_resolution: 1.0
      ndt_step_size: 0.1
      ndt_num_threads: 4
      ndt_max_iterations: 35
      min_align_frequency: 1.0
      transform_epsilon: 0.01
      voxel_leaf_size: 0.2
      scan_max_range: 50.0
      scan_min_range: 1.0
      scan_period: 0.1
      use_pcd_map: true
      map_path: "/maps/mbc_l9/mbc_l9_voxelized_0.2.pcd"
      set_initial_pose: false
      initial_pose_x: 0.0
      initial_pose_y: 0.0
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 0.0
      distance_threshold: 0.5
      use_odom: true
      use_odom_pose: false
      publish_global_odom: true
      publish_global_base: false
      use_imu: false
      enable_debug: false
      global_frame_id: map
      odom_frame_id: odom
      base_frame_id: base_link
